---
swagger: "2.0"
info:
  description: "."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "login"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "task"
  description: "Access to Petstore orders"
schemes:
- "http"
paths:
  /api/user/login:
    get:
      tags:
      - "login"
      summary: ""
      description: ""
      operationId: "login"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "Login"
  /api/task:
    put:
      tags:
      - "task"
      summary: "add task"
      description: ""
      operationId: "addTask"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "Task"
  /api/task/{taskId}:
    get:
      tags:
      - "task"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
      - "application/json"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      x-swagger-router-controller: "Task"
definitions:
  body:
    type: "object"
    properties:
      userId:
        type: "integer"
        format: "int64"
      plan:
        type: "string"
      objects:
        type: "array"
        items:
          $ref: "#/definitions/apitask_objects"
  apitask_objects:
    properties:
      kind:
        type: "string"
      count:
        type: "integer"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
